services:
  server:
    build: .
    environment:
      - DATABASE_URL=postgresql://root:root@database:5432/notes
      - SERVER_HOST=0.0.0.0
    ports:
      - 80:3000
    restart: on-failure
    depends_on:
      - database
  database:
    image: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=notes
    volumes:
      - database-volume:/var/lib/postgresql/data0.54345700005069380.54345700005069380.5434570000506938
    ports:
      - 5432:5432
volumes:
  database-volume:

