services:
  server:
    build: .
    environment:
      - DATABASE_URL=postgresql://root:root@database:5432/notes
      - SERVER_HOST=0.0.0.0
    depends_on:
      - database
    ports:
      - 80:3000
    restart: on-failure
  database:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=notes
    volumes:
      - database-volume:/var/lib/postgresql/data
volumes:
  database-volume:
